export enum NotificationType {
  BOOKING_CONFIRMED = 'BOOKING_CONFIRMED',
  APPOINTMENT_REMINDER = 'APPOINTMENT_REMINDER',
  APPOINTMENT_CANCELLED = 'APPOINTMENT_CANCELLED',
  DOCTOR_FAVORITED = 'DOCTOR_FAVORITED',
}
